version: "3.8"
services:
  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - 1883:1883
    restart: unless-stopped
    command: mosquitto -c /mosquitto/config/mosquitto.conf -v
  node-red:
    image: nodered/node-red
    volumes:
      - ./node-red/data:/data
    ports:
      - 1880:1880
    restart: unless-stopped
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
